### ISSUE TITLE
zplug use

### ISSUE THREAD

**Issue by davidosomething** [lukechilds/zsh-better-npm-completion#1]
since you call compdef you need the `nice` parameter >= 10
that ensures `compdef()` the function exists in the first place

see: https://github.com/zplug/zplug#3-tags-for-zplug
https://github.com/zsh-users/zsh/blob/master/Completion/compinit#L238

**Comment by lukechilds** [comment]
Thanks for pointing that out 👍 

Should be sorted now https://github.com/lukechilds/zsh-better-npm-completion/commit/c20cf68ea4193c0e3c1198db44ac5070ebbb544b
