### ISSUE TITLE
error when export NVM_LAZY_LOAD=true

### ISSUE THREAD

**Issue by lmiranda** [lukechilds/zsh-better-npm-completion#15]
I get the following error when using "export NVM_LAZY_LOAD=true"

https-COLON--SLASH--SLASH-github.com-SLASH-lukechilds-SLASH-zsh-better-npm-completion/zsh-better-npm-completion.plugin.zsh:143: command not found: compdef

**Comment by tracure1337** [comment]
do not use the homebrew NVM.

**Comment by joshuaquek** [comment]
Hi, oh how does one resolve this? I am getting this error too

**Comment by joshuaquek** [comment]
The error I am getting is similar:

```bash
/Users/josh/.zsh/zsh-better-npm-completion/zsh-better-npm-completion.plugin.zsh:143: command not found: compdef
```
