### ISSUE TITLE
Autocompleting npm scripts adds spaces

### ISSUE THREAD

**Issue by ghost** [lukechilds/zsh-better-npm-completion#4]
When I use ```npm run something``` and the scripts object is indented, zsh-better-npm-completion adds the indentation like ```\ \ \ \``` for 4 space indentation in front of the found script.

**Comment by lukechilds** [comment]
Yeah it turns out implementing a JSON parser in zsh is actually pretty tricky 😆

Thanks for reporting, I should have time to take a look at this tomorrow.

**Comment by lukechilds** [comment]
@con-ssc can you paste your `package.json`?

**Comment by ghost** [comment]
Sure
```
{
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "devDependencies": {
    "@types/d3": "^4.5.0",
    "@types/jquery": "^2.0.40",
    "@types/xrm": "^8.0.37"
  },
  "dependencies": {
    "d3": "^4.7.1",
    "stylus": "^0.54.5",
    "typescript": "^2.2.1"
  },
  "scripts": {
    "stylus": "stylus -w hierarchy/src/hierarchy.styl",
    "typescript": "tsc -w -p ./hierarchy",
    "browser-sync": "browser-sync start --server \"hierarchy/dist\" --files \"hierarchy/src/*.*\"",
    "dev": "concurrently --kill-others --prefix \"[{name}]\" --names \"STYLUS,TYPESCRIPT,HTTP\" -c \"bgBlue.bold,bgMagenta.bold,bgGreen.bold\" \"npm run stylus\" \"npm run typescript\" \"npm run browser-sync\""
  }
```

**Comment by lukechilds** [comment]
That's working ok for me, maybe it's a tab/space issue. Are you suing tabs or spaces?

**Comment by ghost** [comment]
I use spaces

**Comment by lukechilds** [comment]
Strange, if I paste that package.json it works. Could you upload the file somewhere and send me the link so I can test the exact file.

**Comment by lukechilds** [comment]
or link me to the repo if it's open source.

**Comment by ghost** [comment]
You are right, it must have been a differen package.json since this has only two spaces indent, I go checking.

**Comment by lukechilds** [comment]
Why do you have more than two spaces of indentation?

**Comment by ghost** [comment]
because I have a global editor config that says 4 spaces indent

**Comment by ghost** [comment]
Right now, the npm autocompletion doesn't work at all :( so I cannot reproduce the error.

**Comment by lukechilds** [comment]
Hmmn, I haven't pushed any updates for a while.

If you revert to default npm formatting does it work?

Running `npm install --save foo` should auto format it for you.

**Comment by lukechilds** [comment]
Ok, so I'm using the amount of spaces to determine the object depth:

```shell
cat package.json | sed -nE "/^  \"scripts\": \{$/,/^  \},?$/p"
```

That returns the scripts object, notice the two spaces hardcoded in. That's to stop us accidentally grabbing the wrong scripts object if the package.json looks something like this:

```json
{
  "version": "1.0.0",
  "name": "some-pkg",
  "scripts": {
    "foo": "bar"
  },
  "babel": {
    "scripts": {
      "fizz": "buzz"
    }
  }
}
``` 

I can't really support your use case without adding a crazy amount of complexity to the plugin. Sorry 😕

**Comment by ghost** [comment]
Thanks for your effort.
would it make sense to actually use jq? because then you would just type
```cat package.json | jq .scripts```
[./jq](https://stedolan.github.io/jq/)

**Comment by lukechilds** [comment]
If I could rely on `jq` being installed on users machines that would be perfect. Unfortunately I don't think it's very common.

**Comment by ghost** [comment]
Good point, but can't you add dependencies to your plugin or something?

**Comment by ghost** [comment]
Or maybe it is just a matter with using zsh on windows

**Comment by lukechilds** [comment]
No, there's no way to add a dependency. I think some plugin managers may support external shell scripts, but this needs to work on lots of different plugin managers + standalone script.
